config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'users/sign_out' => 'users/sessions#destroy'
    get 'send_welcome_email', to: 'users/registrations#send_welcome_email'
    get 'account_cancelled_email', to: 'users/registrations#account_cancelled_email'
  end

  root 'movies#index'
  resources :movies do
    resources :reviews do
      resources :user_review_comments
    end
    post :movie_rating, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user_review_comment.rb
class UserReviewComment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  validates :comment, presence: true
end

app/controllers/user_review_comments_controller.rb
class UserReviewCommentsController < ApplicationController
  before_action :set_movie
  before_action :set_review
  before_action :set_user_review_comment, only: %i[show edit update destroy]

  %i[index show new edit].each do |action|
    define_method(action) do
      instance_variable_set("@user_review_comments", UserReviewComment.all) if action == :index
      @user_review_comment ||= @review.user_review_comments.new if action == :new
    end
  end

  def create
    @user_review_comment = @review.user_review_comments.new(user_review_comment_params)
    @user_review_comment.user = current_user

    respond_to do |format|
      if @user_review_comment.save
        handle_success_response(format, :created, "Review's comment created.")
      else
        handle_error_response(format, :new)
      end
    end
  end

  def update
    respond_to do |format|
      if @user_review_comment.update(user_review_comment_params)
        handle_success_response(format, :ok, "Review's comment updated.")
      else
        handle_error_response(format, :edit)
      end
    end
  end

  def destroy
    @user_review_comment.destroy
    handle_destroy_response
  end

  private

  def handle_success_response(format, status, notice)
    format.html { redirect_to [@movie, @review], notice: notice }
    format.json { render :show, status: status, location: @user_review_comment }
  end

  def handle_error_response(format, render_action)
    format.html { render render_action, status: :unprocessable_entity }
    format.json { render json: @user_review_comment.errors, status: :unprocessable_entity }
  end

  def handle_destroy_response
    respond_to do |format|
      format.html { redirect_to [@movie, @review], notice: "Review's comment destroyed." }
      format.json { head :no_content }
    end
  end

  def set_user_review_comment
    @user_review_comment = UserReviewComment.find(params[:id])
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def set_review
    @review = Review.find(params[:review_id])
  end

  def user_review_comment_params
    params.fetch(:user_review_comment, {}).permit(:comment)
  end
end

app/helpers/user_review_comments_helper.rb
module UserReviewCommentsHelper
end

app/views/user_review_comments/_form.html.erb
<%= form_with(model: [@movie, @review, user_review_comment]) do |form| %>
  <% if user_review_comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_review_comment.errors.count, "error") %> prohibited this user_review_comment from being saved:</h2>

      <ul>
        <% user_review_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_field :comment, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_review_comments/_user_review_comment.html.erb
<div id="<%= dom_id user_review_comment %>">
  <%= user_review_comment.comment %>
</div>

app/views/user_review_comments/edit.html.erb
<h1>Editing user review comment</h1>

<%= render "form", user_review_comment: @user_review_comment %>

<br>

<div>
  <%= link_to "Back to review", movie_review_path(@movie, @review), class: 'btn btn-outline-primary' %>
</div>

app/views/user_review_comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User review comments</h1>

<div id="user_review_comments">
  <% @user_review_comments.each do |user_review_comment| %>
    <%= render user_review_comment %>
    <p>
      <%= link_to "Show this user review comment", user_review_comment %>
    </p>
  <% end %>
</div>

<%= link_to "New user review comment", new_user_review_comment_path %>

app/views/user_review_comments/new.html.erb
<h1>New user review comment</h1>

<%= render "form", user_review_comment: @user_review_comment %>

<br>

<div>
  <%= link_to "Back to user review comments", movie_review_path(@movie, @review), class: 'btn btn-outline-secondary' %>
</div>

app/views/user_review_comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%#= render @user_review_comment %>

<table class="table table-striped">
  <thead>
  <tr>
    <th class="table-primary">Review's Comment</th>
    <th class="table-primary text-center" colspan="3" >Action</th>
  </tr>
  </thead>
<tbody>
  <td class="table-info"><%= render @user_review_comment %></td>
  <td class="table-info"><%= link_to "Back to review", movie_review_path(@movie, @review), class: 'btn btn-outline-secondary' %></td>
  <% if can? :edit, @user_review_comment %>
  <td class="table-info"><%= link_to "Edit this user review comment", edit_movie_review_user_review_comment_path(@user_review_comment), class: 'btn btn-outline-secondary' %></td>
  <td class="table-info"><%= button_to "Destroy this user review comment", movie_review_user_review_comment_path	, method: :delete, class: 'btn btn-outline-secondary' %></td>
<% end %>
  </tbody>
</table>